---
git:
  depth: 1
sudo: true # can't use this due to git upgrade requirement

cache:
  directories:
  - node_modules

env:
 - NODE_VERSION="5"
 - NODE_VERSION="4"

install:
 # install latest git
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install git                                 ; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./scripts/update-linux-git.sh; fi
 - git --version

 # install proper node version
 - rm -rf ~/.nvm
 - git clone https://github.com/creationix/nvm.git ~/.nvm
 - source ~/.nvm/nvm.sh
 - nvm install $NODE_VERSION
 - node --version
 - npm install -g npm@3
 - npm install

os:
 - linux
 - osx

script: make test-ci
